### ISSUE TITLE
cannot find files in the public folder

### ISSUE THREAD

**Issue by xarthurx** [ZTL-UwU/shadcn-docs-nuxt#30]
I tried to provide downloadable files in the public folder.
But it seems the link always lead to a empty page.

How are links handled when they are directed to the `public` folder?
---
Tried both:
1. `[:icon{name="lucide:cloud-download"}](/ghDemo/BAL_soilDemoPart1.gh)`
2. `[Linked File](/ghDemo/BAL_soilDemoPart1.gh)`

Neither worked,

FYI, it was fine when I use `docus`. So I guess there's something wrong here with your template...

**Comment by ZTL-UwU** [comment]
For now you can set `external` to `true`.
- `[:icon{name="lucide:cloud-download"}](/ghDemo/BAL_soilDemoPart1.gh){external=true}`
- `[Linked File](/ghDemo/BAL_soilDemoPart1.gh){external=true}`

**Comment by xarthurx** [comment]
> For now you can set `external` to `true`.
> 
> * `[:icon{name="lucide:cloud-download"}](/ghDemo/BAL_soilDemoPart1.gh){external=true}`
> * `[Linked File](/ghDemo/BAL_soilDemoPart1.gh){external=true}`

Nope.
```
 WARN  [Vue warn]: Invalid prop: type check failed for prop "external". Expected Boolean, got String with value "true".
  at <NuxtLink href="/public/ghDemo/BAL_soilDemoPart1Separates.gh" target=undefined class="font-semibold underline underline-offset-4"  ... >
  at <ProseA href="/public/ghDemo/BAL_soilDemoPart1Separates.gh" external="true" >
  at <AsyncComponentWrapper href="/public/ghDemo/BAL_soilDemoPart1Separates.gh" external="true" >
  at <ProseP >
  at <AsyncComponentWrapper >
  at <MDCRenderer body= { type: 'root',

```

Cannot send a boolean value to the `external`.

**Comment by xarthurx** [comment]
Is this caused by some extra optimization in your template that blocked the access of `public` folder?

**Comment by ZTL-UwU** [comment]
It's because the routes of files in the public folder are caught by the `[...slug].vue`.

**Comment by xarthurx** [comment]
> It's because the routes of files in the public folder are caught by the `[...slug].vue` page.

It shoulden't... `public` are by default exposable for `nuxt` or `nuxt content` project and should be excluded for webpage route auto-generation.
It was all fine for `docus` template, so I assume something you did reverted the function.

**Comment by ZTL-UwU** [comment]
No, I dont believe that docus has a `[...slug].vue` page. Also, if you refresh the empty page, you can refresh it and I think you can see the files after.

> It shoulden't... public are by default exposable for nuxt or nuxt content project and should be excluded for webpage route auto-generation.

I don't think it should either. I'm not sure why it is caught.

**Comment by xarthurx** [comment]
> No, I dont believe that docus has a `[...slug].vue` page. Also, if you refresh the empty page, I think you can see the files after.
> 
> > It shoulden't... public are by default exposable for nuxt or nuxt content project and should be excluded for webpage route auto-generation.
> 
> I don't think it should either. I'm not sure why it is caught.

Refresh doesn't make it work.

**Comment by ZTL-UwU** [comment]
perhaps it works differently in a nuxt layer

**Comment by xarthurx** [comment]
I got this warning from the cmd when I clicked the link:

```
 WARN  [Vue warn]: Extraneous non-props attributes (data-v-inspector) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.
  at <ToastProvider label=undefined duration=undefined swipeDirection=undefined  ... >
  at <ToastProvider data-v-inspector="node_modules/shadcn-docs-nuxt/app.vue:18:3" >
  at <Toaster data-v-inspector="node_modules/shadcn-docs-nuxt/app.vue:18:3" >
  at <App data-v-inspector="node_modules/nuxt/dist/app/components/nuxt-root.vue:16:5" >
  at <NuxtRoot>
```

**Comment by ZTL-UwU** [comment]
This is not relevant

**Comment by ZTL-UwU** [comment]
> > It's because the routes of files in the public folder are caught by the `[...slug].vue` page.
> 
> It shoulden't... `public` are by default exposable for `nuxt` or `nuxt content` project and should be excluded for webpage route auto-generation. It was all fine for `docus` template, so I assume something you did reverted the function.

Actually, I think this is expected behavior from nuxt. see https://stackblitz.com/edit/nuxt-starter-1rvxlv?file=app.vue,pages%2F[...slug].vue

I'll add the `external` prop to `proseA` and it should work.

**Comment by xarthurx** [comment]
I'm also testing and realized that if I just click, it has the problem.
But if I right-click and "open in new tab", similar to sending a `_blank` to the html and open a new page, then I can download the file.

**Comment by ZTL-UwU** [comment]
@xarthurx Please try upgrading to `v0.5.4` and use `[:icon{name="lucide:cloud-download"}](/ghDemo/BAL_soilDemoPart1.gh){external=true}`. See if it fixes it for you.

**Comment by ZTL-UwU** [comment]
> I'm also testing and realized that if I just click, it has the problem. But if I right-click and "open in new tab", similar to sending a `_blank` to the html and open a new page, then I can download the file.

Yes, that's equivalent to refreshing or the `external` prop which triggers a a full-page reload.

**Comment by xarthurx** [comment]
BTW, I'm using the `card` component like:
![image](https://github.com/user-attachments/assets/19fe5506-357e-4375-a770-0be965f2ed7d)

**Comment by xarthurx** [comment]
Nevermind. 
I finally overcome this by writing a customized component.
Thank you for the effort.
